version: '3'

services:
  realsense:
    container_name: realsense
    hostname: realsense
    build:
      context: ./realsense
    networks:
      - real_sense
    privileged: true
    volumes:
      - /dev/input:/dev/input