version: '3'

services:

  master_node:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./MasterNode
    environment:
      - "PYTHONUNBUFFERED=3"
    networks:
      - cluster
    links:
      - central_logic
      - gui
      - motor_api
      - ocular
      - navigation
      - simulation

  gui:
    build:
      dockerfile: Dockerfile.dev
      context: ./Gui
    environment:
      - "PYTHONUNBUFFERED=3"
      - RESOLUTION=1280x850
      - XAUTHORITY=/run/user/1000
    volumes:
      - /dev/shm:/dev/shm
      - /dorowu/ubuntu-desktop-lxde-vnc
    ports:
      - 6081:80
      - 5901:5900
    healthcheck:
      disable: true
    networks:
      - cluster
    privileged: true

  simulation:
    build:
      dockerfile: Dockerfile.dev
      context: ./Simulation
    ports:
      - 6080:80
      - 5900:5900
    environment:
      - "PYTHONUNBUFFERED=3"
      - RESOLUTION=1280x850
      - XAUTHORITY=/run/user/1000
    healthcheck:
      disable: true
    volumes:
      - /dev/shm:/dev/shm
      - /dorowu/ubuntu-desktop-lxde-vnc
    networks:
      - cluster

  central_logic:
    build:
      dockerfile: Dockerfile.dev
      context: ./Central_Logic
    environment:
      - "PYTHONUNBUFFERED=3"
    networks:
      - cluster

  motor_api:
    build:
      dockerfile: Dockerfile.dev
      context: ./MotorAPI
    environment:
      - "PYTHONUNBUFFERED=3"
    networks:
      - cluster

  navigation:
    build:
      dockerfile: Dockerfile.dev
      context: ./Navigation
    environment:
      - "PYTHONUNBUFFERED=3"
    networks:
      - cluster

  ocular:
    build:
      dockerfile: Dockerfile.dev
      context: ./Ocular
    environment:
      - "PYTHONUNBUFFERED=3"
    networks:
      - cluster

volumes:
  project:
    driver: local

networks:
  cluster:
    driver: "bridge"
