version: '3'

services:
  talker:
    build: ./publisher
    environment:
      - "PYTHONUNBUFFERED=1"
    networks:
      - cluster
    command: ros2 run demo_nodes_py talker

  subscriber:
    build: ./subscriber
    environment:
      - "PYTHONUNBUFFERED=1"
    networks:
      - cluster
    command: ros2 run demo_nodes_cpp listener

  master_node:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./ros1-master
    environment:
      - "PYTHONUNBUFFERED=3"
    networks:
      - cluster

  ros1-subscriber:
    build: ./ros1-subscriber
    environment:
      - "PYTHONUNBUFFERED=1"
    networks:
      - cluster
    command: rosrun project main.py

  bridge:
    image: ros:foxy-ros1-bridge
    environment:
      - "ROS_HOSTNAME=bridge"
      - "ROS_MASTER_URI=http://master_node:11311"
    networks:
      - cluster
    command: ros2 run ros1_bridge dynamic_bridge

networks:
  cluster:
    driver: "bridge"